name: Push Test

on:
  workflow_dispatch:

jobs:
  push-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create dummy file
        run: echo "Testing push at $(date)" >> debug.txt

      - name: Commit and Push
        env:
          GH_PAT: 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
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://${GH_PAT}@github.com/${{ github.repository }}
          git add debug.txt
          if git diff --cached --quiet; then
            echo "⚠️ Nothing to commit. Skipping push."
          else
            git commit -m "🔧 Debug push test"
            git push
          fi
