name: Push Test

on:
  workflow_dispatch:

jobs:
  push-test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Git
      run: sudo apt update && sudo apt install -y git

    - name: Clone the repository using PAT
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git clone https://x-access-token:${GH_PAT}@github.com/praveency046/daily-recon.git repo
        cd repo

        echo "Test run at $(date)" >> test.txt

        git config user.name "Praveen B"
        git config user.email "praveenpraveen8407@gmail.com"

        git add test.txt
        git commit -m "✅ Auto push test via GitHub Actions" || echo "⚠️ Nothing to commit"
        git push origin main
