name: Push Test

on:
  workflow_dispatch:

jobs:
  push-test:
    runs-on: ubuntu-latest

    env:
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Set up Git config
        run: |
          git config --global user.name "Praveen B"
          git config --global user.email "praveenpraveen8407@gmail.com"

      - name: Clone the repository with PAT
        run: |
          git clone https://x-access-token:${GH_PAT}@github.com/praveency046/daily-recon.git repo
          cd repo

          echo "Pushed from GitHub Actions at $(date)" > test.txt
          git add test.txt
          git commit -m "✅ Auto push test from Actions" || echo "Nothing to commit"
          git push https://x-access-token:${GH_PAT}@github.com/praveency046/daily-recon.git
